export default {
	// fetch data actions
	FETCH_DATA: "FETCH_DATA",
	LOAD_POSTS: "LOAD_POSTS",
	LOAD_POSTS_SUCCESS: "LOAD_POSTS_SUCCESS",
	LOAD_POSTS_ERROR: "LOAD_POSTS_ERROR",

	// login actions
	LOGIN: "LOGIN",

	// posts actions
	ADD_NEW_POST: "ADD_NEW_POST",
	DELETE_POST: "DELETE_POST",

	// FACEBOOK APP DATA
	APP_ID: "552216338261451",
};
