export default {
	// fetch post data actions
	FETCH_POSTS: "FETCH_POSTS",
	LOAD_POSTS_SUCCESS: "LOAD_POSTS_SUCCESS",
	LOAD_POSTS_ERROR: "LOAD_POSTS_ERROR",

	// fetch comments data
	FETCH_COMMENTS: "FETCH_COMMENTS",
	LOAD_COMMENTS_SUCCESS: "LOAD_COMMENTS_SUCCESS",
	LOAD_COMMENTS_ERROR: "LOAD_COMMENTS_ERROR",

	// login actions
	LOGIN: "LOGIN",

	// facebook app data
	APP_ID: "552216338261451",

	OPEN_POST: "OPEN_POST",
};